server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一，不一定要和服务名一致
          uri: lb://user-service #路由的目标地址，lb表示启用负载均衡，//表示服务名称
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，若请求以user开头则转发至user-service
          filters:
            - AddRequestHeader=MyHeaderKey,my header value
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
            - After=2071-01-20T17:42:47.789-07:00[America/Denver]
      default-filters:
        - AddRequestHeader=MyHeaderKey, my header value
